"""Bundle the model data into a JS module for the web app.

The browser build has no server and no build step, so it cannot fetch JSON from
disk (file:// blocks it). Emitting the data as a JS module means index.html
opens straight from a folder and still works.

Run this after scripts/build_model.py. CI checks the result is current, so the
web app can never quietly drift from the Python model.

Usage:
    python scripts/sync_web_data.py
    python scripts/sync_web_data.py --check    # exit 1 if stale
"""

import json
import os
import sys

ROOT = os.path.join(os.path.dirname(__file__), "..")
DATA = os.path.join(ROOT, "cantojam", "data")
TARGET = os.path.join(ROOT, "web", "data.js")
LEXICON_TARGET = os.path.join(ROOT, "web", "lexicon.js")

HEADER = """// Generated by scripts/sync_web_data.py. Do not edit by hand.
//
// CHAR_TONES and MODEL are derived from Jason Lee's Cantopop corpus
// (https://github.com/jasonleeubc/Cantopop-corpus), CC BY 4.0.
// COLLOQUIAL is hand-authored for cantojam, MIT. See ATTRIBUTION.md.
"""


def render():
    parts = [HEADER]
    for name, filename in (("CHAR_TONES", "char_tones.json"),
                           ("MODEL", "model.json"),
                           ("COLLOQUIAL", "colloquial.json")):
        with open(os.path.join(DATA, filename), encoding="utf-8") as handle:
            payload = json.load(handle)
        if name == "COLLOQUIAL":
            payload = {k: v for k, v in payload.items()
                       if not k.startswith("_")}
        dumped = json.dumps(payload, ensure_ascii=False, sort_keys=True,
                            separators=(",", ":"))
        parts.append(f"export const {name} = {dumped};\n")
    return "\n".join(parts)


def render_lexicon():
    with open(os.path.join(DATA, "lexicon.json"), encoding="utf-8") as handle:
        payload = json.load(handle)
    dumped = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return (HEADER.replace("CHAR_TONES and MODEL are", "LEXICON is")
            + f"export const LEXICON = {dumped};\n")


def write(target, generated, check):
    current = None
    if os.path.exists(target):
        with open(target, encoding="utf-8") as handle:
            current = handle.read()
    name = os.path.relpath(target, ROOT)
    if current == generated:
        print(f"{name} is up to date ({len(generated) / 1024:.0f} KB)")
        return 0
    if check:
        print(f"ERROR: {name} is stale. Run: python scripts/sync_web_data.py")
        return 1
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as handle:
        handle.write(generated)
    print(f"wrote {name} ({len(generated) / 1024:.0f} KB)")
    return 0


def main():
    check = "--check" in sys.argv
    status = write(TARGET, render(), check)
    status |= write(LEXICON_TARGET, render_lexicon(), check)
    return status



if __name__ == "__main__":
    sys.exit(main())
